### ISSUE TITLE
Please check result of this application

### ISSUE THREAD

**Issue by yangwoolee** [sjfricke/VARTIP#1]
Hello.
I tried your application. It looks processing camera stream and preview using vulkan.
Is it right? but still I don't know it's meaning of operation and if it working correctly or not.
Could you check my capture image from your application?
![screenshot_20190118-145245_vartip](https://user-images.githubusercontent.com/45278108/51368194-b2493380-1b31-11e9-9a34-871b48546a70.jpg)

below is original scene which is captured by android default camera
![20190118_145258_original](https://user-images.githubusercontent.com/45278108/51368195-b5dcba80-1b31-11e9-8cc8-b42a75433723.jpg)

**Comment by sjfricke** [comment]
Hey @yangwoolee, yes... I was debugging this application as some stride offset was wrong... Thanks for being interested in this project. Hopefully, I have some time this weekend even to try and debug this, but have been not able to spend much time on my hobby repos lately :disappointed:

**Comment by yangwoolee** [comment]
Thank you for reply.
Even it is your hobby, I interested in your project. Im an newbie in vulkan
camera.
Anyway, it alreay very helpful.

2019년 1월 19일 (토) 오후 2:00에 Spencer <notifications@github.com>님이 작성:

**Comment by sjfricke** [comment]
Ya, well Vulkan is hard to get into in itself and Android NDK Camera is not any better :laughing:

**Comment by yangwoolee** [comment]
Sorry, I could not understand. What's mean "Android NDK Camera is not any better"?
Are you saying that Java Camera2 implementation is better then NDK Camera?

**Comment by sjfricke** [comment]
No, I ment to say it is hard in itself to get the NDK Camera to work. The NDK Camera is going to be faster **IF** you do it correctly, which is hard

**Comment by sjfricke** [comment]
Hey @yangwoolee
So currently got it to work!
Added a big todo, curious why the camera is grabbing the way it is

**Comment by yangwoolee** [comment]
It's good.
I checked your working camera preview with vulkan.
Thank you for your effort.

2019년 2월 3일 (일) 오후 2:00, Spencer <notifications@github.com>님이 작성:
